[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  framework = "vite"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Explicitly disable the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/send-email/test.html"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com https://iqekgptnsqfkafjjwdon.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://* blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://iqekgptnsqfkafjjwdon.supabase.co https://maps.googleapis.com https://api.mapbox.com;
      frame-src 'self';
      media-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200 