\n\n-- Create vehicle makes table\nCREATE TABLE IF NOT EXISTS vehicle_makes (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  name text NOT NULL UNIQUE,\n  created_at timestamptz DEFAULT now()\n);
\n\n-- Create vehicle models table\nCREATE TABLE IF NOT EXISTS vehicle_models (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  make_id uuid REFERENCES vehicle_makes(id) ON DELETE CASCADE NOT NULL,\n  name text NOT NULL,\n  created_at timestamptz DEFAULT now(),\n  UNIQUE(make_id, name)\n);
\n\n-- Enable RLS\nALTER TABLE vehicle_makes ENABLE ROW LEVEL SECURITY;
\nALTER TABLE vehicle_models ENABLE ROW LEVEL SECURITY;
\n\n-- Create indexes\nCREATE INDEX IF NOT EXISTS idx_vehicle_makes_name ON vehicle_makes(name);
\nCREATE INDEX IF NOT EXISTS idx_vehicle_models_make ON vehicle_models(make_id);
\nCREATE INDEX IF NOT EXISTS idx_vehicle_models_name ON vehicle_models(name);
\n\n-- Create RLS policies\nCREATE POLICY "Allow public read access to vehicle makes"\n  ON vehicle_makes FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "Allow public read access to vehicle models"\n  ON vehicle_models FOR SELECT\n  TO public\n  USING (true);
\n\n-- Insert some common car makes and models\nINSERT INTO vehicle_makes (name) VALUES\n  ('Dacia'),\n  ('Volkswagen'),\n  ('Toyota'),\n  ('Ford'),\n  ('BMW'),\n  ('Mercedes-Benz'),\n  ('Audi'),\n  ('Skoda'),\n  ('Renault'),\n  ('Hyundai')\nON CONFLICT (name) DO NOTHING;
\n\n-- Insert models for each make\nDO $$\nDECLARE\n  dacia_id uuid;
\n  vw_id uuid;
\n  toyota_id uuid;
\n  ford_id uuid;
\n  bmw_id uuid;
\n  mercedes_id uuid;
\n  audi_id uuid;
\n  skoda_id uuid;
\n  renault_id uuid;
\n  hyundai_id uuid;
\nBEGIN\n  -- Get make IDs\n  SELECT id INTO dacia_id FROM vehicle_makes WHERE name = 'Dacia';
\n  SELECT id INTO vw_id FROM vehicle_makes WHERE name = 'Volkswagen';
\n  SELECT id INTO toyota_id FROM vehicle_makes WHERE name = 'Toyota';
\n  SELECT id INTO ford_id FROM vehicle_makes WHERE name = 'Ford';
\n  SELECT id INTO bmw_id FROM vehicle_makes WHERE name = 'BMW';
\n  SELECT id INTO mercedes_id FROM vehicle_makes WHERE name = 'Mercedes-Benz';
\n  SELECT id INTO audi_id FROM vehicle_makes WHERE name = 'Audi';
\n  SELECT id INTO skoda_id FROM vehicle_makes WHERE name = 'Skoda';
\n  SELECT id INTO renault_id FROM vehicle_makes WHERE name = 'Renault';
\n  SELECT id INTO hyundai_id FROM vehicle_makes WHERE name = 'Hyundai';
\n\n  -- Insert models\n  -- Dacia\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (dacia_id, 'Logan'),\n    (dacia_id, 'Sandero'),\n    (dacia_id, 'Duster'),\n    (dacia_id, 'Spring'),\n    (dacia_id, 'Jogger')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Volkswagen\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (vw_id, 'Golf'),\n    (vw_id, 'Passat'),\n    (vw_id, 'Tiguan'),\n    (vw_id, 'Polo'),\n    (vw_id, 'T-Roc')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Toyota\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (toyota_id, 'Corolla'),\n    (toyota_id, 'RAV4'),\n    (toyota_id, 'Camry'),\n    (toyota_id, 'Yaris'),\n    (toyota_id, 'C-HR')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Ford\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (ford_id, 'Focus'),\n    (ford_id, 'Fiesta'),\n    (ford_id, 'Kuga'),\n    (ford_id, 'Puma'),\n    (ford_id, 'Mondeo')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- BMW\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (bmw_id, 'Seria 3'),\n    (bmw_id, 'Seria 5'),\n    (bmw_id, 'X3'),\n    (bmw_id, 'X5'),\n    (bmw_id, 'X1')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Mercedes-Benz\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (mercedes_id, 'Clasa C'),\n    (mercedes_id, 'Clasa E'),\n    (mercedes_id, 'GLC'),\n    (mercedes_id, 'GLA'),\n    (mercedes_id, 'Clasa A')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Audi\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (audi_id, 'A3'),\n    (audi_id, 'A4'),\n    (audi_id, 'Q3'),\n    (audi_id, 'Q5'),\n    (audi_id, 'A6')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Skoda\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (skoda_id, 'Octavia'),\n    (skoda_id, 'Superb'),\n    (skoda_id, 'Kodiaq'),\n    (skoda_id, 'Karoq'),\n    (skoda_id, 'Fabia')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Renault\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (renault_id, 'Clio'),\n    (renault_id, 'Megane'),\n    (renault_id, 'Captur'),\n    (renault_id, 'Kadjar'),\n    (renault_id, 'Talisman')\n  ON CONFLICT (make_id, name) DO NOTHING;
\n\n  -- Hyundai\n  INSERT INTO vehicle_models (make_id, name) VALUES\n    (hyundai_id, 'i30'),\n    (hyundai_id, 'Tucson'),\n    (hyundai_id, 'Kona'),\n    (hyundai_id, 'i20'),\n    (hyundai_id, 'Santa Fe')\n  ON CONFLICT (make_id, name) DO NOTHING;
\nEND $$;
;
