-- Drop existing trip policies if they exist\nDO $$ \nBEGIN\n  DROP POLICY IF EXISTS "trips_select_policy" ON trips;
\n  DROP POLICY IF EXISTS "trips_insert_policy" ON trips;
\n  DROP POLICY IF EXISTS "trips_update_policy" ON trips;
\n  DROP POLICY IF EXISTS "trips_delete_policy" ON trips;
\n  DROP POLICY IF EXISTS "trips_select" ON trips;
\n  DROP POLICY IF EXISTS "trips_insert" ON trips;
\n  DROP POLICY IF EXISTS "trips_update" ON trips;
\n  DROP POLICY IF EXISTS "trips_delete" ON trips;
\n  DROP POLICY IF EXISTS "Trips are viewable by everyone" ON trips;
\n  DROP POLICY IF EXISTS "Users with complete profiles can create trips" ON trips;
\n  DROP POLICY IF EXISTS "Everyone can view trip cities" ON trips;
\n  DROP POLICY IF EXISTS "Drivers can create trips with cities" ON trips;
\n  DROP POLICY IF EXISTS "Drivers can see full addresses" ON trips;
\n  DROP POLICY IF EXISTS "Address visibility" ON trips;
\n  DROP POLICY IF EXISTS "Anyone can view trips" ON trips;
\nEND $$;
\n\n-- Create new open policies for trips\nCREATE POLICY "open_trips_select"\n  ON trips FOR SELECT\n  TO public\n  USING (true);
\n\nCREATE POLICY "open_trips_insert"\n  ON trips FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    auth.uid() = driver_id\n  );
\n\nCREATE POLICY "open_trips_update"\n  ON trips FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = driver_id)\n  WITH CHECK (auth.uid() = driver_id);
\n\nCREATE POLICY "open_trips_delete"\n  ON trips FOR DELETE\n  TO authenticated\n  USING (auth.uid() = driver_id);
\n\n-- Add indexes for better performance if they don't exist\nCREATE INDEX IF NOT EXISTS idx_trips_search \n  ON trips(from_city, to_city, date);
\n\nCREATE INDEX IF NOT EXISTS idx_trips_driver \n  ON trips(driver_id);
\n\n-- Refresh materialized view\nREFRESH MATERIALIZED VIEW trip_seats;
;
