\n\n-- Drop all existing booking policies\nDO $$ \nBEGIN\n  DROP POLICY IF EXISTS "bookings_insert" ON bookings;
\n  DROP POLICY IF EXISTS "bookings_select" ON bookings;
\n  DROP POLICY IF EXISTS "bookings_update" ON bookings;
\nEND $$;
\n\n-- Create helper function for counting accepted bookings\nCREATE OR REPLACE FUNCTION get_accepted_bookings(trip_id bigint)\nRETURNS bigint AS $$\n  SELECT COUNT(*)\n  FROM bookings\n  WHERE trip_id = $1 AND status = 'accepted';
\n$$ LANGUAGE sql STABLE;
\n\n-- Create new simplified booking policies\nCREATE POLICY "bookings_insert_policy"\n  ON bookings FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    auth.uid() = user_id AND\n    EXISTS (\n      SELECT 1 FROM trips t\n      WHERE t.id = trip_id\n      AND t.driver_id != auth.uid()\n      AND t.seats > get_accepted_bookings(t.id)\n    )\n  );
\n\nCREATE POLICY "bookings_select_policy"\n  ON bookings FOR SELECT\n  TO authenticated\n  USING (\n    auth.uid() = user_id OR\n    EXISTS (\n      SELECT 1 FROM trips t\n      WHERE t.id = trip_id AND t.driver_id = auth.uid()\n    )\n  );
\n\nCREATE POLICY "bookings_update_policy"\n  ON bookings FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM trips t\n      WHERE t.id = trip_id AND t.driver_id = auth.uid()\n    )\n  )\n  WITH CHECK (\n    status IN ('accepted', 'rejected', 'cancelled')\n  );
\n\n-- Add trigger to prevent overbooking\nCREATE OR REPLACE FUNCTION check_booking_seats()\nRETURNS trigger AS $$\nBEGIN\n  IF NEW.status = 'accepted' AND (\n    SELECT t.seats <= get_accepted_bookings(t.id)\n    FROM trips t\n    WHERE t.id = NEW.trip_id\n  ) THEN\n    RAISE EXCEPTION 'No available seats for this trip';
\n  END IF;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\nDROP TRIGGER IF EXISTS booking_seats_check ON bookings;
\nCREATE TRIGGER booking_seats_check\n  BEFORE UPDATE OF status ON bookings\n  FOR EACH ROW\n  WHEN (NEW.status = 'accepted')\n  EXECUTE FUNCTION check_booking_seats();
\n\n-- Add policy for public trip viewing\nCREATE POLICY "trips_select_policy"\n  ON trips FOR SELECT\n  TO public\n  USING (true);
\n\n-- Refresh materialized view\nREFRESH MATERIALIZED VIEW trip_seats;
;
